# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
  config.vm.box_version = "3.5.0"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.boot_timeout = 600
  config.vm.define "eklompusS" do |control|
    control.vm.hostname = "eklompusS"
    control.vm.network "private_network", ip: "192.168.42.110"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "eklompusS"]
    end
    control.vm.provision "shell", path: "scripts/eklompuss.sh"
    control.vm.provision "shell", path: "scripts/init_bash.sh"
  end
  config.vm.define "eklompusSW" do |control|
    control.vm.hostname = "eklompusSW"
    control.vm.network "private_network", ip: "192.168.42.111"
    control.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "eklompusSW"]
    end
    control.vm.provision "master-key", type: "file", source: ".vagrant/machines/eklompusS/virtualbox/private_key", destination: "/home/vagrant/.ssh/master.key"
    control.vm.provision "shell", path: "scripts/eklompussw.sh"
  end
end
